/*
 * This file was automatically generated by EvoSuite
 * Thu Oct 01 04:43:29 GMT 2026
 */

package org.apache.commons.collections.map;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import java.util.Collection;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Locale;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Set;
import java.util.function.Consumer;
import org.apache.commons.collections.MapIterator;
import org.apache.commons.collections.map.AbstractHashedMap;
import org.apache.commons.collections.map.Flat3Map;
import org.apache.commons.collections.map.HashedMap;
import org.evosuite.runtime.ViolatedAssumptionAnswer;

public class Flat3Map_ESTest {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      AbstractHashedMap abstractHashedMap0 = new AbstractHashedMap(924, 924, 924);
      Flat3Map flat3Map0 = new Flat3Map(abstractHashedMap0);
      Flat3Map.FlatMapIterator flat3Map_FlatMapIterator0 = new Flat3Map.FlatMapIterator(flat3Map0);
      // Undeclared exception!
      try { 
        flat3Map_FlatMapIterator0.getValue();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // getValue() can only be called after next() and before remove()
         //
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      Flat3Map.FlatMapIterator flat3Map_FlatMapIterator0 = new Flat3Map.FlatMapIterator(flat3Map0);
      flat3Map_FlatMapIterator0.reset();
      assertFalse(flat3Map_FlatMapIterator0.hasNext());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      Flat3Map.EntrySet flat3Map_EntrySet0 = new Flat3Map.EntrySet(flat3Map0);
      int int0 = flat3Map_EntrySet0.size();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      AbstractHashedMap abstractHashedMap0 = new AbstractHashedMap();
      Flat3Map flat3Map0 = new Flat3Map(abstractHashedMap0);
      Flat3Map.EntrySet flat3Map_EntrySet0 = new Flat3Map.EntrySet(flat3Map0);
      flat3Map_EntrySet0.clear();
      assertEquals(0, flat3Map_EntrySet0.size());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      Flat3Map.KeySet flat3Map_KeySet0 = new Flat3Map.KeySet(flat3Map0);
      boolean boolean0 = flat3Map_KeySet0.remove((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      Flat3Map.KeySet flat3Map_KeySet0 = new Flat3Map.KeySet(flat3Map0);
      flat3Map_KeySet0.clear();
      assertEquals(0, flat3Map_KeySet0.size());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      Flat3Map.KeySet flat3Map_KeySet0 = new Flat3Map.KeySet(flat3Map0);
      Iterator iterator0 = flat3Map_KeySet0.iterator();
      boolean boolean0 = flat3Map_KeySet0.contains(iterator0);
      assertFalse(boolean0);
      assertEquals(0, flat3Map_KeySet0.size());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      AbstractHashedMap abstractHashedMap0 = flat3Map0.createDelegateMap();
      assertEquals(0, abstractHashedMap0.size());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      Flat3Map.Values flat3Map_Values0 = new Flat3Map.Values(flat3Map0);
      boolean boolean0 = flat3Map_Values0.contains("{}");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      Flat3Map.Values flat3Map_Values0 = new Flat3Map.Values(flat3Map0);
      flat3Map_Values0.clear();
      assertEquals(0, flat3Map_Values0.size());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      Flat3Map.ValuesIterator flat3Map_ValuesIterator0 = new Flat3Map.ValuesIterator(flat3Map0);
      // Undeclared exception!
      try { 
        flat3Map_ValuesIterator0.getKey();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // getKey() can only be called after next() and before remove()
         //
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      Set set0 = flat3Map0.entrySet();
      Flat3Map.ValuesIterator flat3Map_ValuesIterator0 = new Flat3Map.ValuesIterator(flat3Map0);
      flat3Map0.put(set0, set0);
      Consumer<Object> consumer0 = (Consumer<Object>) mock(Consumer.class, new ViolatedAssumptionAnswer());
      flat3Map_ValuesIterator0.forEachRemaining(consumer0);
      Object object0 = flat3Map_ValuesIterator0.setValue((Object) null);
      assertSame(object0, set0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      AbstractHashedMap abstractHashedMap0 = new AbstractHashedMap();
      Flat3Map flat3Map0 = new Flat3Map(abstractHashedMap0);
      HashedMap hashedMap0 = new HashedMap(625, 625);
      Object object0 = flat3Map0.getOrDefault((Object) null, hashedMap0);
      assertSame(hashedMap0, object0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      Set set0 = flat3Map0.entrySet();
      flat3Map0.put(set0, set0);
      HashedMap hashedMap0 = new HashedMap(1, 144.10977F);
      Object object0 = flat3Map0.putIfAbsent(hashedMap0, hashedMap0);
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      Set set0 = flat3Map0.entrySet();
      flat3Map0.put(set0, set0);
      HashedMap hashedMap0 = new HashedMap(1, 144.10977F);
      flat3Map0.put(hashedMap0, (Object) null);
      flat3Map0.putIfAbsent(hashedMap0, hashedMap0);
      assertEquals(2, flat3Map0.size());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      boolean boolean0 = flat3Map0.isEmpty();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      boolean boolean0 = flat3Map0.containsValue((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      HashedMap hashedMap0 = new HashedMap(5263);
      flat3Map0.put(hashedMap0, (Object) null);
      boolean boolean0 = flat3Map0.containsValue((Object) null);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      HashedMap hashedMap0 = new HashedMap(1779, 1779);
      flat3Map0.put((Object) null, hashedMap0);
      flat3Map0.put((Object) null, "{}");
      assertFalse(flat3Map0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      HashedMap hashedMap0 = new HashedMap();
      Flat3Map flat3Map0 = new Flat3Map(hashedMap0);
      flat3Map0.put(hashedMap0, hashedMap0);
      flat3Map0.put(hashedMap0, (Object) null);
      assertEquals(1, flat3Map0.size());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      HashMap<Object, Locale.Category> hashMap0 = new HashMap<Object, Locale.Category>();
      Locale.Category locale_Category0 = Locale.Category.DISPLAY;
      hashMap0.put((Object) null, locale_Category0);
      Flat3Map flat3Map0 = new Flat3Map(hashMap0);
      Flat3Map.FlatMapIterator flat3Map_FlatMapIterator0 = new Flat3Map.FlatMapIterator(flat3Map0);
      boolean boolean0 = flat3Map_FlatMapIterator0.hasNext();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      MapIterator mapIterator0 = flat3Map0.mapIterator();
      assertNotNull(mapIterator0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      Flat3Map.FlatMapIterator flat3Map_FlatMapIterator0 = new Flat3Map.FlatMapIterator(flat3Map0);
      // Undeclared exception!
      try { 
        flat3Map_FlatMapIterator0.next();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No next() entry in the iteration
         //
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      Set set0 = flat3Map0.entrySet();
      Flat3Map.FlatMapIterator flat3Map_FlatMapIterator0 = new Flat3Map.FlatMapIterator(flat3Map0);
      flat3Map0.put(set0, set0);
      Object object0 = flat3Map_FlatMapIterator0.next();
      assertFalse(flat3Map_FlatMapIterator0.hasNext());
      assertNotNull(object0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      Flat3Map.FlatMapIterator flat3Map_FlatMapIterator0 = new Flat3Map.FlatMapIterator(flat3Map0);
      // Undeclared exception!
      try { 
        flat3Map_FlatMapIterator0.remove();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // remove() can only be called once after next()
         //
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      Flat3Map.FlatMapIterator flat3Map_FlatMapIterator0 = new Flat3Map.FlatMapIterator(flat3Map0);
      // Undeclared exception!
      try { 
        flat3Map_FlatMapIterator0.getKey();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // getKey() can only be called after next() and before remove()
         //
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      Flat3Map.FlatMapIterator flat3Map_FlatMapIterator0 = new Flat3Map.FlatMapIterator(flat3Map0);
      // Undeclared exception!
      try { 
        flat3Map_FlatMapIterator0.setValue((Object) null);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // setValue() can only be called after next() and before remove()
         //
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      Flat3Map.FlatMapIterator flat3Map_FlatMapIterator0 = new Flat3Map.FlatMapIterator(flat3Map0);
      String string0 = flat3Map_FlatMapIterator0.toString();
      assertEquals("Iterator[]", string0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      Flat3Map.EntrySet flat3Map_EntrySet0 = new Flat3Map.EntrySet(flat3Map0);
      boolean boolean0 = flat3Map_EntrySet0.remove(flat3Map0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      Flat3Map.EntrySet flat3Map_EntrySet0 = new Flat3Map.EntrySet(flat3Map0);
      Object[] objectArray0 = new Object[8];
      flat3Map_EntrySet0.toArray(objectArray0);
      assertEquals(0, flat3Map_EntrySet0.size());
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      Flat3Map.KeySetIterator flat3Map_KeySetIterator0 = new Flat3Map.KeySetIterator(flat3Map0);
      // Undeclared exception!
      try { 
        flat3Map_KeySetIterator0.remove();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // remove() can only be called once after next()
         //
      }
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      AbstractHashedMap abstractHashedMap0 = new AbstractHashedMap(87, (-3668.116F), 0);
      HashMap<HashedMap, Object> hashMap0 = new HashMap<HashedMap, Object>(abstractHashedMap0);
      Flat3Map flat3Map0 = new Flat3Map(hashMap0);
      Flat3Map.ValuesIterator flat3Map_ValuesIterator0 = new Flat3Map.ValuesIterator(flat3Map0);
      // Undeclared exception!
      try { 
        flat3Map_ValuesIterator0.getValue();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // getValue() can only be called after next() and before remove()
         //
      }
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      Flat3Map.EntrySetIterator flat3Map_EntrySetIterator0 = new Flat3Map.EntrySetIterator(flat3Map0);
      HashedMap hashedMap0 = new HashedMap();
      // Undeclared exception!
      try { 
        flat3Map_EntrySetIterator0.setValue(hashedMap0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // setValue() can only be called after next() and before remove()
         //
      }
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      HashedMap hashedMap0 = new HashedMap(2422);
      Flat3Map.EntrySetIterator flat3Map_EntrySetIterator0 = new Flat3Map.EntrySetIterator(flat3Map0);
      boolean boolean0 = flat3Map_EntrySetIterator0.equals(hashedMap0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      Flat3Map.ValuesIterator flat3Map_ValuesIterator0 = new Flat3Map.ValuesIterator(flat3Map0);
      String string0 = flat3Map_ValuesIterator0.toString();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      Set set0 = flat3Map0.keySet();
      assertEquals(0, set0.size());
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      HashMap<Object, Locale.Category> hashMap0 = new HashMap<Object, Locale.Category>();
      Flat3Map flat3Map0 = new Flat3Map(hashMap0);
      Collection collection0 = flat3Map0.values();
      assertNotNull(collection0);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      Object object0 = flat3Map0.clone();
      assertNotSame(object0, flat3Map0);
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      Locale.Category locale_Category0 = Locale.Category.FORMAT;
      boolean boolean0 = flat3Map0.equals(locale_Category0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      AbstractHashedMap abstractHashedMap0 = new AbstractHashedMap(3505);
      Flat3Map flat3Map0 = new Flat3Map(abstractHashedMap0);
      boolean boolean0 = flat3Map0.equals(abstractHashedMap0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      flat3Map0.hashCode();
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      String string0 = flat3Map0.toString();
      assertEquals("{}", string0);
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      HashedMap hashedMap0 = new HashedMap();
      Flat3Map flat3Map0 = new Flat3Map(hashedMap0);
      flat3Map0.put(hashedMap0, hashedMap0);
      String string0 = flat3Map0.toString();
      assertEquals("{{}={}}", string0);
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      HashedMap hashedMap0 = new HashedMap(1, 1);
      Flat3Map flat3Map0 = new Flat3Map(hashedMap0);
      boolean boolean0 = flat3Map0.containsValue(hashedMap0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      AbstractHashedMap abstractHashedMap0 = new AbstractHashedMap();
      Flat3Map flat3Map0 = new Flat3Map(abstractHashedMap0);
      flat3Map0.putAll(abstractHashedMap0);
      assertEquals(0, abstractHashedMap0.size());
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      Flat3Map.KeySet flat3Map_KeySet0 = new Flat3Map.KeySet(flat3Map0);
      Iterator iterator0 = flat3Map_KeySet0.iterator();
      flat3Map0.remove((Object) iterator0);
      assertEquals(0, flat3Map_KeySet0.size());
      assertEquals(0, flat3Map0.size());
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      flat3Map0.clear();
      assertTrue(flat3Map0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      Flat3Map flat3Map0 = null;
      try {
        flat3Map0 = new Flat3Map((Map) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      HashedMap hashedMap0 = new HashedMap(558);
      boolean boolean0 = flat3Map0.containsKey(hashedMap0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      HashedMap hashedMap0 = new HashedMap();
      Flat3Map flat3Map0 = new Flat3Map(hashedMap0);
      flat3Map0.put(hashedMap0, hashedMap0);
      Set set0 = flat3Map0.entrySet();
      assertFalse(set0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      Locale.Category locale_Category0 = Locale.Category.FORMAT;
      Object object0 = flat3Map0.get(locale_Category0);
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      Set set0 = flat3Map0.entrySet();
      flat3Map0.put(set0, set0);
      int int0 = flat3Map0.size();
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      int int0 = flat3Map0.size();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      Set set0 = flat3Map0.entrySet();
      flat3Map0.put(set0, set0);
      Flat3Map.KeySetIterator flat3Map_KeySetIterator0 = new Flat3Map.KeySetIterator(flat3Map0);
      flat3Map_KeySetIterator0.next();
      assertFalse(flat3Map_KeySetIterator0.hasNext());
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      Flat3Map.EntrySet flat3Map_EntrySet0 = new Flat3Map.EntrySet(flat3Map0);
      flat3Map_EntrySet0.iterator();
      assertEquals(0, flat3Map_EntrySet0.size());
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      Flat3Map.KeySetIterator flat3Map_KeySetIterator0 = new Flat3Map.KeySetIterator(flat3Map0);
      boolean boolean0 = flat3Map_KeySetIterator0.hasNext();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test57()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      Flat3Map.ValuesIterator flat3Map_ValuesIterator0 = new Flat3Map.ValuesIterator(flat3Map0);
      // Undeclared exception!
      try { 
        flat3Map_ValuesIterator0.next();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No next() entry in the iteration
         //
      }
  }

  @Test(timeout = 4000)
  public void test58()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      Flat3Map.KeySet flat3Map_KeySet0 = new Flat3Map.KeySet(flat3Map0);
      int int0 = flat3Map_KeySet0.size();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test59()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      Flat3Map.Values flat3Map_Values0 = new Flat3Map.Values(flat3Map0);
      flat3Map_Values0.iterator();
      assertEquals(0, flat3Map_Values0.size());
  }

  @Test(timeout = 4000)
  public void test60()  throws Throwable  {
      HashMap<Object, HashedMap> hashMap0 = new HashMap<Object, HashedMap>();
      Flat3Map flat3Map0 = new Flat3Map(hashMap0);
      Flat3Map.Values flat3Map_Values0 = new Flat3Map.Values(flat3Map0);
      int int0 = flat3Map_Values0.size();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test61()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      Flat3Map.ValuesIterator flat3Map_ValuesIterator0 = new Flat3Map.ValuesIterator(flat3Map0);
      // Undeclared exception!
      try { 
        flat3Map_ValuesIterator0.next();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No next() entry in the iteration
         //
      }
  }
}
