<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
<modelVersion>4.0.0</modelVersion><groupId>sqa.closure</groupId><artifactId>closure-gemini-preparation</artifactId><version>1.0-SNAPSHOT</version>
<properties><project.build.sourceEncoding>UTF-8</project.build.sourceEncoding><maven.compiler.source>8</maven.compiler.source><maven.compiler.target>8</maven.compiler.target></properties>
<dependencies><dependency><groupId>junit</groupId><artifactId>junit</artifactId><version>3.8.2</version><scope>test</scope></dependency></dependencies>
<build><plugins><plugin><groupId>org.codehaus.mojo</groupId><artifactId>build-helper-maven-plugin</artifactId><version>3.6.0</version><executions><execution><id>add-bug-sources</id><phase>generate-test-sources</phase><goals><goal>add-test-source</goal></goals><configuration><sources>
                                <source>${project.basedir}/TestCode/Closure-1</source>
                                <source>${project.basedir}/TestCode/Closure-2</source>
                                <source>${project.basedir}/TestCode/Closure-3</source>
                                <source>${project.basedir}/TestCode/Closure-4</source>
                                <source>${project.basedir}/TestCode/Closure-5</source>
                                <source>${project.basedir}/TestCode/Closure-6</source>
                                <source>${project.basedir}/TestCode/Closure-7</source>
                                <source>${project.basedir}/TestCode/Closure-8</source>
                                <source>${project.basedir}/TestCode/Closure-9</source>
                                <source>${project.basedir}/TestCode/Closure-10</source>
                                <source>${project.basedir}/TestCode/Closure-11</source>
                                <source>${project.basedir}/TestCode/Closure-12</source>
                                <source>${project.basedir}/TestCode/Closure-13</source>
                                <source>${project.basedir}/TestCode/Closure-14</source>
                                <source>${project.basedir}/TestCode/Closure-15</source>
                                <source>${project.basedir}/TestCode/Closure-16</source>
                                <source>${project.basedir}/TestCode/Closure-17</source>
                                <source>${project.basedir}/TestCode/Closure-18</source>
                                <source>${project.basedir}/TestCode/Closure-19</source>
                                <source>${project.basedir}/TestCode/Closure-20</source>
                                <source>${project.basedir}/TestCode/Closure-21</source>
                                <source>${project.basedir}/TestCode/Closure-22</source>
                                <source>${project.basedir}/TestCode/Closure-23</source>
                                <source>${project.basedir}/TestCode/Closure-24</source>
                                <source>${project.basedir}/TestCode/Closure-25</source>
                                <source>${project.basedir}/TestCode/Closure-26</source>
                                <source>${project.basedir}/TestCode/Closure-27</source>
                                <source>${project.basedir}/TestCode/Closure-28</source>
                                <source>${project.basedir}/TestCode/Closure-29</source>
                                <source>${project.basedir}/TestCode/Closure-30</source>
                                <source>${project.basedir}/TestCode/Closure-31</source>
                                <source>${project.basedir}/TestCode/Closure-32</source>
                                <source>${project.basedir}/TestCode/Closure-33</source>
                                <source>${project.basedir}/TestCode/Closure-34</source>
                                <source>${project.basedir}/TestCode/Closure-35</source>
                                <source>${project.basedir}/TestCode/Closure-36</source>
                                <source>${project.basedir}/TestCode/Closure-37</source>
                                <source>${project.basedir}/TestCode/Closure-38</source>
                                <source>${project.basedir}/TestCode/Closure-39</source>
                                <source>${project.basedir}/TestCode/Closure-40</source>
                                <source>${project.basedir}/TestCode/Closure-41</source>
                                <source>${project.basedir}/TestCode/Closure-42</source>
                                <source>${project.basedir}/TestCode/Closure-43</source>
                                <source>${project.basedir}/TestCode/Closure-44</source>
                                <source>${project.basedir}/TestCode/Closure-45</source>
                                <source>${project.basedir}/TestCode/Closure-46</source>
                                <source>${project.basedir}/TestCode/Closure-47</source>
                                <source>${project.basedir}/TestCode/Closure-48</source>
                                <source>${project.basedir}/TestCode/Closure-49</source>
                                <source>${project.basedir}/TestCode/Closure-50</source>
                                <source>${project.basedir}/TestCode/Closure-51</source>
                                <source>${project.basedir}/TestCode/Closure-52</source>
                                <source>${project.basedir}/TestCode/Closure-53</source>
                                <source>${project.basedir}/TestCode/Closure-54</source>
                                <source>${project.basedir}/TestCode/Closure-55</source>
                                <source>${project.basedir}/TestCode/Closure-56</source>
                                <source>${project.basedir}/TestCode/Closure-57</source>
                                <source>${project.basedir}/TestCode/Closure-58</source>
                                <source>${project.basedir}/TestCode/Closure-59</source>
                                <source>${project.basedir}/TestCode/Closure-60</source>
                                <source>${project.basedir}/TestCode/Closure-61</source>
                                <source>${project.basedir}/TestCode/Closure-62</source>
                                <source>${project.basedir}/TestCode/Closure-64</source>
                                <source>${project.basedir}/TestCode/Closure-65</source>
                                <source>${project.basedir}/TestCode/Closure-66</source>
                                <source>${project.basedir}/TestCode/Closure-67</source>
                                <source>${project.basedir}/TestCode/Closure-68</source>
                                <source>${project.basedir}/TestCode/Closure-69</source>
                                <source>${project.basedir}/TestCode/Closure-70</source>
                                <source>${project.basedir}/TestCode/Closure-71</source>
                                <source>${project.basedir}/TestCode/Closure-72</source>
                                <source>${project.basedir}/TestCode/Closure-73</source>
                                <source>${project.basedir}/TestCode/Closure-74</source>
                                <source>${project.basedir}/TestCode/Closure-75</source>
                                <source>${project.basedir}/TestCode/Closure-76</source>
                                <source>${project.basedir}/TestCode/Closure-77</source>
                                <source>${project.basedir}/TestCode/Closure-78</source>
                                <source>${project.basedir}/TestCode/Closure-79</source>
                                <source>${project.basedir}/TestCode/Closure-80</source>
                                <source>${project.basedir}/TestCode/Closure-81</source>
                                <source>${project.basedir}/TestCode/Closure-82</source>
                                <source>${project.basedir}/TestCode/Closure-83</source>
                                <source>${project.basedir}/TestCode/Closure-84</source>
                                <source>${project.basedir}/TestCode/Closure-85</source>
                                <source>${project.basedir}/TestCode/Closure-86</source>
                                <source>${project.basedir}/TestCode/Closure-87</source>
                                <source>${project.basedir}/TestCode/Closure-88</source>
                                <source>${project.basedir}/TestCode/Closure-89</source>
                                <source>${project.basedir}/TestCode/Closure-90</source>
                                <source>${project.basedir}/TestCode/Closure-91</source>
                                <source>${project.basedir}/TestCode/Closure-92</source>
                                <source>${project.basedir}/TestCode/Closure-94</source>
                                <source>${project.basedir}/TestCode/Closure-95</source>
                                <source>${project.basedir}/TestCode/Closure-96</source>
                                <source>${project.basedir}/TestCode/Closure-97</source>
                                <source>${project.basedir}/TestCode/Closure-98</source>
                                <source>${project.basedir}/TestCode/Closure-99</source>
                                <source>${project.basedir}/TestCode/Closure-100</source>
                                <source>${project.basedir}/TestCode/Closure-101</source>
                                <source>${project.basedir}/TestCode/Closure-102</source>
                                <source>${project.basedir}/TestCode/Closure-103</source>
                                <source>${project.basedir}/TestCode/Closure-104</source>
                                <source>${project.basedir}/TestCode/Closure-105</source>
                                <source>${project.basedir}/TestCode/Closure-106</source>
                                <source>${project.basedir}/TestCode/Closure-107</source>
                                <source>${project.basedir}/TestCode/Closure-108</source>
                                <source>${project.basedir}/TestCode/Closure-109</source>
                                <source>${project.basedir}/TestCode/Closure-110</source>
                                <source>${project.basedir}/TestCode/Closure-111</source>
                                <source>${project.basedir}/TestCode/Closure-112</source>
                                <source>${project.basedir}/TestCode/Closure-113</source>
                                <source>${project.basedir}/TestCode/Closure-114</source>
                                <source>${project.basedir}/TestCode/Closure-115</source>
                                <source>${project.basedir}/TestCode/Closure-116</source>
                                <source>${project.basedir}/TestCode/Closure-117</source>
                                <source>${project.basedir}/TestCode/Closure-118</source>
                                <source>${project.basedir}/TestCode/Closure-119</source>
                                <source>${project.basedir}/TestCode/Closure-120</source>
                                <source>${project.basedir}/TestCode/Closure-121</source>
                                <source>${project.basedir}/TestCode/Closure-122</source>
                                <source>${project.basedir}/TestCode/Closure-123</source>
                                <source>${project.basedir}/TestCode/Closure-124</source>
                                <source>${project.basedir}/TestCode/Closure-125</source>
                                <source>${project.basedir}/TestCode/Closure-126</source>
                                <source>${project.basedir}/TestCode/Closure-127</source>
                                <source>${project.basedir}/TestCode/Closure-128</source>
                                <source>${project.basedir}/TestCode/Closure-129</source>
                                <source>${project.basedir}/TestCode/Closure-130</source>
                                <source>${project.basedir}/TestCode/Closure-131</source>
                                <source>${project.basedir}/TestCode/Closure-132</source>
                                <source>${project.basedir}/TestCode/Closure-133</source>
                                <source>${project.basedir}/TestCode/Closure-134</source>
                                <source>${project.basedir}/TestCode/Closure-135</source>
                                <source>${project.basedir}/TestCode/Closure-136</source>
                                <source>${project.basedir}/TestCode/Closure-137</source>
                                <source>${project.basedir}/TestCode/Closure-138</source>
                                <source>${project.basedir}/TestCode/Closure-139</source>
                                <source>${project.basedir}/TestCode/Closure-140</source>
                                <source>${project.basedir}/TestCode/Closure-141</source>
                                <source>${project.basedir}/TestCode/Closure-142</source>
                                <source>${project.basedir}/TestCode/Closure-143</source>
                                <source>${project.basedir}/TestCode/Closure-144</source>
                                <source>${project.basedir}/TestCode/Closure-145</source>
                                <source>${project.basedir}/TestCode/Closure-146</source>
                                <source>${project.basedir}/TestCode/Closure-147</source>
                                <source>${project.basedir}/TestCode/Closure-148</source>
                                <source>${project.basedir}/TestCode/Closure-149</source>
                                <source>${project.basedir}/TestCode/Closure-150</source>
                                <source>${project.basedir}/TestCode/Closure-151</source>
                                <source>${project.basedir}/TestCode/Closure-152</source>
                                <source>${project.basedir}/TestCode/Closure-153</source>
                                <source>${project.basedir}/TestCode/Closure-154</source>
                                <source>${project.basedir}/TestCode/Closure-155</source>
                                <source>${project.basedir}/TestCode/Closure-156</source>
                                <source>${project.basedir}/TestCode/Closure-157</source>
                                <source>${project.basedir}/TestCode/Closure-158</source>
                                <source>${project.basedir}/TestCode/Closure-159</source>
                                <source>${project.basedir}/TestCode/Closure-160</source>
                                <source>${project.basedir}/TestCode/Closure-161</source>
                                <source>${project.basedir}/TestCode/Closure-162</source>
                                <source>${project.basedir}/TestCode/Closure-163</source>
                                <source>${project.basedir}/TestCode/Closure-164</source>
                                <source>${project.basedir}/TestCode/Closure-165</source>
                                <source>${project.basedir}/TestCode/Closure-166</source>
                                <source>${project.basedir}/TestCode/Closure-167</source>
                                <source>${project.basedir}/TestCode/Closure-168</source>
                                <source>${project.basedir}/TestCode/Closure-169</source>
                                <source>${project.basedir}/TestCode/Closure-170</source>
                                <source>${project.basedir}/TestCode/Closure-171</source>
                                <source>${project.basedir}/TestCode/Closure-172</source>
                                <source>${project.basedir}/TestCode/Closure-173</source>
                                <source>${project.basedir}/TestCode/Closure-174</source>
                                <source>${project.basedir}/TestCode/Closure-175</source>
                                <source>${project.basedir}/TestCode/Closure-176</source>
</sources></configuration></execution></executions></plugin><plugin><groupId>org.apache.maven.plugins</groupId><artifactId>maven-compiler-plugin</artifactId><version>3.13.0</version></plugin></plugins></build></project>
