/*
 * This file was automatically generated by EvoSuite
 * Wed Sep 30 21:40:12 GMT 2026
 */

package org.apache.commons.collections.map;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import java.nio.ByteBuffer;
import java.nio.CharBuffer;
import java.nio.charset.Charset;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Set;
import java.util.function.BiConsumer;
import java.util.function.BiFunction;
import org.apache.commons.collections.MapIterator;
import org.apache.commons.collections.map.AbstractHashedMap;
import org.apache.commons.collections.map.Flat3Map;
import org.apache.commons.collections.map.HashedMap;
import org.evosuite.runtime.ViolatedAssumptionAnswer;

public class Flat3Map_ESTest {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      Flat3Map.FlatMapIterator flat3Map_FlatMapIterator0 = new Flat3Map.FlatMapIterator(flat3Map0);
      flat3Map0.put((Object) null, (Object) null);
      flat3Map_FlatMapIterator0.next();
      HashedMap hashedMap0 = new HashedMap(flat3Map0);
      flat3Map_FlatMapIterator0.setValue(hashedMap0);
      assertEquals(1, flat3Map0.size());
      assertFalse(flat3Map0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Flat3Map.FlatMapIterator flat3Map_FlatMapIterator0 = new Flat3Map.FlatMapIterator((Flat3Map) null);
      flat3Map_FlatMapIterator0.reset();
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      Flat3Map.EntrySet flat3Map_EntrySet0 = new Flat3Map.EntrySet(flat3Map0);
      int int0 = flat3Map_EntrySet0.size();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      Flat3Map.EntrySet flat3Map_EntrySet0 = new Flat3Map.EntrySet(flat3Map0);
      flat3Map_EntrySet0.clear();
      assertEquals(0, flat3Map_EntrySet0.size());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      Flat3Map.KeySet flat3Map_KeySet0 = new Flat3Map.KeySet(flat3Map0);
      int int0 = flat3Map_KeySet0.size();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      Flat3Map.EntrySet flat3Map_EntrySet0 = new Flat3Map.EntrySet(flat3Map0);
      Flat3Map.KeySet flat3Map_KeySet0 = new Flat3Map.KeySet(flat3Map0);
      boolean boolean0 = flat3Map_KeySet0.remove(flat3Map_EntrySet0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      Flat3Map.KeySet flat3Map_KeySet0 = new Flat3Map.KeySet(flat3Map0);
      flat3Map_KeySet0.clear();
      assertEquals(0, flat3Map_KeySet0.size());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      HashedMap hashedMap0 = new HashedMap(176);
      Flat3Map flat3Map0 = new Flat3Map(hashedMap0);
      Flat3Map.KeySet flat3Map_KeySet0 = new Flat3Map.KeySet(flat3Map0);
      boolean boolean0 = flat3Map_KeySet0.contains(hashedMap0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      AbstractHashedMap abstractHashedMap0 = flat3Map0.createDelegateMap();
      byte[] byteArray0 = new byte[8];
      ByteBuffer byteBuffer0 = ByteBuffer.wrap(byteArray0);
      flat3Map0.putIfAbsent(byteBuffer0, abstractHashedMap0);
      boolean boolean0 = flat3Map0.isEmpty();
      assertEquals(1, flat3Map0.size());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      Flat3Map.Values flat3Map_Values0 = new Flat3Map.Values(flat3Map0);
      boolean boolean0 = flat3Map_Values0.contains(flat3Map0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      Flat3Map.Values flat3Map_Values0 = new Flat3Map.Values(flat3Map0);
      flat3Map_Values0.clear();
      assertEquals(0, flat3Map_Values0.size());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      Flat3Map.Values flat3Map_Values0 = new Flat3Map.Values(flat3Map0);
      int int0 = flat3Map_Values0.size();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      Flat3Map.EntrySetIterator flat3Map_EntrySetIterator0 = new Flat3Map.EntrySetIterator(flat3Map0);
      String string0 = flat3Map_EntrySetIterator0.toString();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      HashedMap hashedMap0 = new HashedMap(4);
      hashedMap0.size = 817;
      Flat3Map flat3Map0 = new Flat3Map(hashedMap0);
      flat3Map0.get(hashedMap0);
      assertEquals(0, flat3Map0.size());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      BiFunction<ByteBuffer, HashedMap, Object> biFunction0 = (BiFunction<ByteBuffer, HashedMap, Object>) mock(BiFunction.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(biFunction0).apply(any(java.nio.ByteBuffer.class) , any(org.apache.commons.collections.map.HashedMap.class));
      Object object0 = flat3Map0.compute((Object) null, biFunction0);
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      flat3Map0.put((Object) null, (Object) null);
      BiFunction<ByteBuffer, HashedMap, Object> biFunction0 = (BiFunction<ByteBuffer, HashedMap, Object>) mock(BiFunction.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(biFunction0).apply(any(java.nio.ByteBuffer.class) , any(org.apache.commons.collections.map.HashedMap.class));
      flat3Map0.compute((Object) null, biFunction0);
      assertEquals(0, flat3Map0.size());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      flat3Map0.put(flat3Map0, (Object) null);
      Object object0 = flat3Map0.get(flat3Map0);
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      boolean boolean0 = flat3Map0.isEmpty();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      boolean boolean0 = flat3Map0.containsValue((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      HashedMap hashedMap0 = new HashedMap(flat3Map0);
      flat3Map0.put((Object) null, (Object) null);
      BiFunction<ByteBuffer, HashedMap, Object> biFunction0 = (BiFunction<ByteBuffer, HashedMap, Object>) mock(BiFunction.class, new ViolatedAssumptionAnswer());
      doReturn(hashedMap0).when(biFunction0).apply(any(java.nio.ByteBuffer.class) , any(org.apache.commons.collections.map.HashedMap.class));
      flat3Map0.compute((Object) null, biFunction0);
      assertEquals(1, flat3Map0.size());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      HashMap<Object, HashedMap> hashMap0 = new HashMap<Object, HashedMap>();
      Flat3Map flat3Map0 = new Flat3Map(hashMap0);
      Charset charset0 = Charset.defaultCharset();
      char[] charArray0 = new char[9];
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      ByteBuffer byteBuffer0 = charset0.encode(charBuffer0);
      hashMap0.put(byteBuffer0, (HashedMap) null);
      flat3Map0.putAll(hashMap0);
      assertFalse(flat3Map0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      AbstractHashedMap abstractHashedMap0 = flat3Map0.createDelegateMap();
      byte[] byteArray0 = new byte[8];
      ByteBuffer byteBuffer0 = ByteBuffer.wrap(byteArray0);
      flat3Map0.putIfAbsent(byteBuffer0, abstractHashedMap0);
      Flat3Map.ValuesIterator flat3Map_ValuesIterator0 = new Flat3Map.ValuesIterator(flat3Map0);
      flat3Map0.remove((Object) flat3Map_ValuesIterator0);
      assertTrue(flat3Map_ValuesIterator0.hasNext());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      AbstractHashedMap abstractHashedMap0 = flat3Map0.createDelegateMap();
      flat3Map0.putIfAbsent(abstractHashedMap0, abstractHashedMap0);
      Object object0 = flat3Map0.remove((Object) null);
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      HashedMap hashedMap0 = new HashedMap(4);
      hashedMap0.size = 817;
      Flat3Map flat3Map0 = new Flat3Map(hashedMap0);
      flat3Map0.clear();
      assertEquals(0, flat3Map0.size());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      MapIterator mapIterator0 = flat3Map0.mapIterator();
      assertNotNull(mapIterator0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      HashedMap hashedMap0 = new HashedMap(4);
      hashedMap0.size = 817;
      Flat3Map flat3Map0 = new Flat3Map(hashedMap0);
      flat3Map0.mapIterator();
      assertEquals(0, flat3Map0.size());
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      Flat3Map.FlatMapIterator flat3Map_FlatMapIterator0 = new Flat3Map.FlatMapIterator(flat3Map0);
      // Undeclared exception!
      try { 
        flat3Map_FlatMapIterator0.next();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No next() entry in the iteration
         //
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      Flat3Map.FlatMapIterator flat3Map_FlatMapIterator0 = new Flat3Map.FlatMapIterator(flat3Map0);
      // Undeclared exception!
      try { 
        flat3Map_FlatMapIterator0.remove();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // remove() can only be called once after next()
         //
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      HashedMap hashedMap0 = new HashedMap(4);
      Flat3Map flat3Map0 = new Flat3Map(hashedMap0);
      Flat3Map.FlatMapIterator flat3Map_FlatMapIterator0 = new Flat3Map.FlatMapIterator(flat3Map0);
      // Undeclared exception!
      try { 
        flat3Map_FlatMapIterator0.getKey();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // getKey() can only be called after next() and before remove()
         //
      }
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      Flat3Map.FlatMapIterator flat3Map_FlatMapIterator0 = new Flat3Map.FlatMapIterator(flat3Map0);
      // Undeclared exception!
      try { 
        flat3Map_FlatMapIterator0.getValue();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // getValue() can only be called after next() and before remove()
         //
      }
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      AbstractHashedMap abstractHashedMap0 = flat3Map0.createDelegateMap();
      Flat3Map.FlatMapIterator flat3Map_FlatMapIterator0 = new Flat3Map.FlatMapIterator(flat3Map0);
      // Undeclared exception!
      try { 
        flat3Map_FlatMapIterator0.setValue(abstractHashedMap0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // setValue() can only be called after next() and before remove()
         //
      }
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      Flat3Map.FlatMapIterator flat3Map_FlatMapIterator0 = new Flat3Map.FlatMapIterator(flat3Map0);
      String string0 = flat3Map_FlatMapIterator0.toString();
      assertEquals("Iterator[]", string0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      HashedMap hashedMap0 = new HashedMap(4);
      hashedMap0.size = 817;
      Flat3Map flat3Map0 = new Flat3Map(hashedMap0);
      Set set0 = flat3Map0.entrySet();
      assertTrue(set0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      Flat3Map.EntrySet flat3Map_EntrySet0 = new Flat3Map.EntrySet(flat3Map0);
      boolean boolean0 = flat3Map_EntrySet0.remove((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      BiConsumer<Object, ByteBuffer> biConsumer0 = (BiConsumer<Object, ByteBuffer>) mock(BiConsumer.class, new ViolatedAssumptionAnswer());
      flat3Map0.forEach(biConsumer0);
      assertTrue(flat3Map0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      AbstractHashedMap abstractHashedMap0 = new AbstractHashedMap();
      Flat3Map flat3Map0 = new Flat3Map(abstractHashedMap0);
      Flat3Map.KeySetIterator flat3Map_KeySetIterator0 = new Flat3Map.KeySetIterator(flat3Map0);
      // Undeclared exception!
      try { 
        flat3Map_KeySetIterator0.remove();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // remove() can only be called once after next()
         //
      }
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      HashMap<Object, Object> hashMap0 = new HashMap<Object, Object>();
      Flat3Map flat3Map0 = new Flat3Map(hashMap0);
      Flat3Map.EntrySetIterator flat3Map_EntrySetIterator0 = new Flat3Map.EntrySetIterator(flat3Map0);
      // Undeclared exception!
      try { 
        flat3Map_EntrySetIterator0.getKey();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // getKey() can only be called after next() and before remove()
         //
      }
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      Flat3Map.KeySetIterator flat3Map_KeySetIterator0 = new Flat3Map.KeySetIterator(flat3Map0);
      // Undeclared exception!
      try { 
        flat3Map_KeySetIterator0.getValue();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // getValue() can only be called after next() and before remove()
         //
      }
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      Flat3Map.KeySetIterator flat3Map_KeySetIterator0 = new Flat3Map.KeySetIterator(flat3Map0);
      // Undeclared exception!
      try { 
        flat3Map_KeySetIterator0.setValue(flat3Map0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // setValue() can only be called after next() and before remove()
         //
      }
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      Flat3Map.ValuesIterator flat3Map_ValuesIterator0 = new Flat3Map.ValuesIterator(flat3Map0);
      boolean boolean0 = flat3Map_ValuesIterator0.equals(flat3Map0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      Set set0 = flat3Map0.keySet();
      assertEquals(0, set0.size());
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      HashedMap hashedMap0 = new HashedMap(12);
      Flat3Map flat3Map0 = new Flat3Map(hashedMap0);
      Flat3Map.KeySet flat3Map_KeySet0 = new Flat3Map.KeySet(flat3Map0);
      flat3Map_KeySet0.iterator();
      assertEquals(0, flat3Map_KeySet0.size());
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      Collection collection0 = flat3Map0.values();
      assertNotNull(collection0);
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      Flat3Map.Values flat3Map_Values0 = new Flat3Map.Values(flat3Map0);
      flat3Map_Values0.iterator();
      assertEquals(0, flat3Map_Values0.size());
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      Object object0 = flat3Map0.clone();
      assertNotSame(object0, flat3Map0);
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      Flat3Map.ValuesIterator flat3Map_ValuesIterator0 = new Flat3Map.ValuesIterator(flat3Map0);
      boolean boolean0 = flat3Map0.equals(flat3Map_ValuesIterator0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      AbstractHashedMap abstractHashedMap0 = new AbstractHashedMap();
      Flat3Map flat3Map0 = new Flat3Map(abstractHashedMap0);
      boolean boolean0 = flat3Map0.equals(abstractHashedMap0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      flat3Map0.hashCode();
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      AbstractHashedMap abstractHashedMap0 = flat3Map0.createDelegateMap();
      byte[] byteArray0 = new byte[8];
      ByteBuffer byteBuffer0 = ByteBuffer.wrap(byteArray0);
      flat3Map0.putIfAbsent(byteBuffer0, abstractHashedMap0);
      flat3Map0.hashCode();
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      HashMap<Object, Object> hashMap0 = new HashMap<Object, Object>();
      Flat3Map flat3Map0 = new Flat3Map(hashMap0);
      String string0 = flat3Map0.toString();
      assertEquals("{}", string0);
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      HashMap<Object, Object> hashMap0 = new HashMap<Object, Object>();
      Flat3Map flat3Map0 = new Flat3Map(hashMap0);
      BiFunction<ByteBuffer, HashedMap, Object> biFunction0 = (BiFunction<ByteBuffer, HashedMap, Object>) mock(BiFunction.class, new ViolatedAssumptionAnswer());
      flat3Map0.merge((Object) null, flat3Map0, biFunction0);
      String string0 = flat3Map0.toString();
      assertEquals("{null=(this Map)}", string0);
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      flat3Map0.put(flat3Map0, (Object) null);
      String string0 = flat3Map0.toString();
      assertEquals("{(this Map)=null}", string0);
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      Flat3Map.EntrySet flat3Map_EntrySet0 = new Flat3Map.EntrySet(flat3Map0);
      boolean boolean0 = flat3Map0.containsValue(flat3Map_EntrySet0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      HashedMap hashedMap0 = new HashedMap(12);
      Flat3Map flat3Map0 = new Flat3Map(hashedMap0);
      flat3Map0.putAll(hashedMap0);
      assertEquals(0, flat3Map0.size());
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      Object object0 = flat3Map0.remove((Object) flat3Map0);
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      flat3Map0.clear();
      assertTrue(flat3Map0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      Flat3Map flat3Map0 = null;
      try {
        flat3Map0 = new Flat3Map((Map) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test57()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      boolean boolean0 = flat3Map0.containsKey("");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test58()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      AbstractHashedMap abstractHashedMap0 = new AbstractHashedMap(flat3Map0);
      Object object0 = new Object();
      abstractHashedMap0.put(object0, object0);
      Flat3Map flat3Map1 = new Flat3Map(abstractHashedMap0);
      Set set0 = flat3Map1.keySet();
      assertEquals(1, set0.size());
  }

  @Test(timeout = 4000)
  public void test59()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      int int0 = flat3Map0.size();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test60()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      Flat3Map.KeySet flat3Map_KeySet0 = new Flat3Map.KeySet(flat3Map0);
      flat3Map0.put(flat3Map_KeySet0, flat3Map_KeySet0);
      Flat3Map.KeySetIterator flat3Map_KeySetIterator0 = new Flat3Map.KeySetIterator(flat3Map0);
      assertTrue(flat3Map_KeySetIterator0.hasNext());
      
      flat3Map_KeySetIterator0.next();
      assertFalse(flat3Map_KeySetIterator0.hasNext());
  }

  @Test(timeout = 4000)
  public void test61()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      AbstractHashedMap abstractHashedMap0 = flat3Map0.createDelegateMap();
      byte[] byteArray0 = new byte[8];
      ByteBuffer byteBuffer0 = ByteBuffer.wrap(byteArray0);
      flat3Map0.putIfAbsent(byteBuffer0, abstractHashedMap0);
      Flat3Map.ValuesIterator flat3Map_ValuesIterator0 = new Flat3Map.ValuesIterator(flat3Map0);
      flat3Map_ValuesIterator0.next();
      assertFalse(flat3Map_ValuesIterator0.hasNext());
  }

  @Test(timeout = 4000)
  public void test62()  throws Throwable  {
      HashedMap hashedMap0 = new HashedMap();
      Flat3Map flat3Map0 = new Flat3Map(hashedMap0);
      Flat3Map.EntrySet flat3Map_EntrySet0 = new Flat3Map.EntrySet(flat3Map0);
      flat3Map_EntrySet0.iterator();
      assertEquals(0, flat3Map_EntrySet0.size());
  }

  @Test(timeout = 4000)
  public void test63()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      Flat3Map.KeySetIterator flat3Map_KeySetIterator0 = new Flat3Map.KeySetIterator(flat3Map0);
      boolean boolean0 = flat3Map_KeySetIterator0.hasNext();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test64()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      Flat3Map.EntrySetIterator flat3Map_EntrySetIterator0 = new Flat3Map.EntrySetIterator(flat3Map0);
      // Undeclared exception!
      try { 
        flat3Map_EntrySetIterator0.next();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No next() entry in the iteration
         //
      }
  }

  @Test(timeout = 4000)
  public void test65()  throws Throwable  {
      Flat3Map flat3Map0 = new Flat3Map();
      Flat3Map.FlatMapIterator flat3Map_FlatMapIterator0 = new Flat3Map.FlatMapIterator(flat3Map0);
      boolean boolean0 = flat3Map_FlatMapIterator0.hasNext();
      assertFalse(boolean0);
  }
}
