/*
 * This file was automatically generated by EvoSuite
 * Fri Oct 02 12:33:49 GMT 2026
 */

package org.apache.commons.csv;

import org.junit.Test;
import static org.junit.Assert.*;
import java.io.IOException;
import java.io.Reader;
import java.io.StringReader;
import org.apache.commons.csv.CSVFormat;
import org.apache.commons.csv.CSVLexer;
import org.apache.commons.csv.CSVLexer1;
import org.apache.commons.csv.CSVLexer1306663;
import org.apache.commons.csv.CSVLexer1306667;
import org.apache.commons.csv.CSVLexer3;
import org.apache.commons.csv.ExtendedBufferedReader;
import org.apache.commons.csv.Quote;
import org.apache.commons.csv.Token;

public class Lexer_ESTest {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      CSVFormat cSVFormat0 = CSVFormat.DEFAULT;
      Reader reader0 = Reader.nullReader();
      ExtendedBufferedReader extendedBufferedReader0 = new ExtendedBufferedReader(reader0);
      CSVLexer1306667 cSVLexer1306667_0 = new CSVLexer1306667(cSVFormat0, extendedBufferedReader0);
      boolean boolean0 = cSVLexer1306667_0.readEndOfLine(9);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      CSVFormat cSVFormat0 = CSVFormat.DEFAULT;
      Reader reader0 = Reader.nullReader();
      ExtendedBufferedReader extendedBufferedReader0 = new ExtendedBufferedReader(reader0);
      CSVLexer1 cSVLexer1_0 = new CSVLexer1(cSVFormat0, extendedBufferedReader0);
      long long0 = cSVLexer1_0.getLineNumber();
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      CSVFormat cSVFormat0 = CSVFormat.RFC4180;
      Reader reader0 = Reader.nullReader();
      ExtendedBufferedReader extendedBufferedReader0 = new ExtendedBufferedReader(reader0);
      CSVLexer1306663 cSVLexer1306663_0 = new CSVLexer1306663(cSVFormat0, extendedBufferedReader0);
      try { 
        cSVLexer1306663_0.readEscape();
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // EOF whilst processing escape sequence
         //
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Character character0 = Character.valueOf('O');
      Quote quote0 = Quote.MINIMAL;
      String[] stringArray0 = new String[9];
      CSVFormat cSVFormat0 = new CSVFormat('O', character0, quote0, (Character) null, character0, false, false, "7I0`", "EOF whilst processing escape sequence", stringArray0);
      StringReader stringReader0 = new StringReader("!fDk={ ");
      ExtendedBufferedReader extendedBufferedReader0 = new ExtendedBufferedReader(stringReader0);
      CSVLexer3 cSVLexer3_0 = new CSVLexer3(cSVFormat0, extendedBufferedReader0);
      int int0 = cSVLexer3_0.readEscape();
      assertEquals((-1), int0);
      
      int int1 = cSVLexer3_0.readEscape();
      assertEquals(12, int1);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Character character0 = Character.valueOf('A');
      Quote quote0 = Quote.NONE;
      String[] stringArray0 = new String[7];
      CSVFormat cSVFormat0 = new CSVFormat('A', character0, quote0, character0, character0, false, true, "5h8gON/|/`d2)A _X", "5h8gON/|/`d2)A _X", stringArray0);
      StringReader stringReader0 = new StringReader("{bl");
      ExtendedBufferedReader extendedBufferedReader0 = new ExtendedBufferedReader(stringReader0);
      CSVLexer1306663 cSVLexer1306663_0 = new CSVLexer1306663(cSVFormat0, extendedBufferedReader0);
      Reader reader0 = Reader.nullReader();
      ExtendedBufferedReader extendedBufferedReader1 = new ExtendedBufferedReader(reader0);
      CSVLexer3 cSVLexer3_0 = new CSVLexer3(cSVFormat0, extendedBufferedReader1);
      Token token0 = new Token();
      Token token1 = cSVLexer3_0.nextToken(token0);
      cSVLexer1306663_0.nextToken(token1);
      int int0 = cSVLexer1306663_0.readEscape();
      assertEquals(8, int0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      CSVFormat cSVFormat0 = CSVFormat.RFC4180;
      StringReader stringReader0 = new StringReader("org.apache.commons.csv.CSVParser$2");
      ExtendedBufferedReader extendedBufferedReader0 = new ExtendedBufferedReader(stringReader0);
      extendedBufferedReader0.read();
      CSVLexer1306663 cSVLexer1306663_0 = new CSVLexer1306663(cSVFormat0, extendedBufferedReader0);
      int int0 = cSVLexer1306663_0.readEscape();
      assertEquals(13, int0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Character character0 = Character.valueOf('<');
      Quote quote0 = Quote.NONE;
      String[] stringArray0 = new String[8];
      CSVFormat cSVFormat0 = new CSVFormat('<', character0, quote0, character0, character0, true, true, "H", "H", stringArray0);
      StringReader stringReader0 = new StringReader("ptMQNi,4&D W4RXYV&o");
      ExtendedBufferedReader extendedBufferedReader0 = new ExtendedBufferedReader(stringReader0);
      CSVLexer cSVLexer0 = new CSVLexer(cSVFormat0, extendedBufferedReader0);
      int int0 = cSVLexer0.readEscape();
      assertEquals((-1), int0);
      
      CSVLexer1306663 cSVLexer1306663_0 = new CSVLexer1306663(cSVFormat0, extendedBufferedReader0);
      int int1 = cSVLexer1306663_0.readEscape();
      assertEquals(9, int1);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Character character0 = Character.valueOf('O');
      Quote quote0 = Quote.MINIMAL;
      String[] stringArray0 = new String[9];
      CSVFormat cSVFormat0 = new CSVFormat('O', character0, quote0, (Character) null, character0, false, false, "7I0`", "EOF whilst processing escape sequence", stringArray0);
      StringReader stringReader0 = new StringReader("EOF whilst processing escape sequence");
      ExtendedBufferedReader extendedBufferedReader0 = new ExtendedBufferedReader(stringReader0);
      CSVLexer3 cSVLexer3_0 = new CSVLexer3(cSVFormat0, extendedBufferedReader0);
      cSVLexer3_0.readEscape();
      cSVLexer3_0.readEscape();
      Token token0 = new Token();
      Token token1 = cSVLexer3_0.nextToken(token0);
      assertSame(token1, token0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      CSVFormat cSVFormat0 = CSVFormat.TDF;
      StringReader stringReader0 = new StringReader("!\"?n+ZE=Q!Wtg");
      ExtendedBufferedReader extendedBufferedReader0 = new ExtendedBufferedReader(stringReader0);
      CSVLexer1306663 cSVLexer1306663_0 = new CSVLexer1306663(cSVFormat0, extendedBufferedReader0);
      int int0 = cSVLexer1306663_0.readEscape();
      assertEquals((-1), int0);
      
      int int1 = cSVLexer1306663_0.readEscape();
      assertEquals(34, int1);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      CSVFormat cSVFormat0 = CSVFormat.TDF;
      StringReader stringReader0 = new StringReader("!\"?n+ZE=Q!Wtg");
      ExtendedBufferedReader extendedBufferedReader0 = new ExtendedBufferedReader(stringReader0);
      CSVLexer1306663 cSVLexer1306663_0 = new CSVLexer1306663(cSVFormat0, extendedBufferedReader0);
      StringBuilder stringBuilder0 = new StringBuilder();
      cSVLexer1306663_0.trimTrailingSpaces(stringBuilder0);
      assertEquals("", stringBuilder0.toString());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      CSVFormat cSVFormat0 = CSVFormat.EXCEL;
      Reader reader0 = Reader.nullReader();
      ExtendedBufferedReader extendedBufferedReader0 = new ExtendedBufferedReader(reader0);
      CSVLexer1306663 cSVLexer1306663_0 = new CSVLexer1306663(cSVFormat0, extendedBufferedReader0);
      boolean boolean0 = cSVLexer1306663_0.readEndOfLine(10);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Quote quote0 = Quote.MINIMAL;
      String[] stringArray0 = new String[2];
      CSVFormat cSVFormat0 = new CSVFormat('n', (Character) null, quote0, (Character) null, (Character) null, false, false, "s:F>z|Jd[w", "s:F>z|Jd[w", stringArray0);
      StringReader stringReader0 = new StringReader("rdo&V\u0001`");
      ExtendedBufferedReader extendedBufferedReader0 = new ExtendedBufferedReader(stringReader0);
      CSVLexer1306663 cSVLexer1306663_0 = new CSVLexer1306663(cSVFormat0, extendedBufferedReader0);
      boolean boolean0 = cSVLexer1306663_0.isWhitespace(110);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      CSVFormat cSVFormat0 = CSVFormat.DEFAULT;
      Reader reader0 = Reader.nullReader();
      ExtendedBufferedReader extendedBufferedReader0 = new ExtendedBufferedReader(reader0);
      CSVLexer1 cSVLexer1_0 = new CSVLexer1(cSVFormat0, extendedBufferedReader0);
      boolean boolean0 = cSVLexer1_0.isStartOfLine(10);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      CSVFormat cSVFormat0 = CSVFormat.EXCEL;
      StringReader stringReader0 = new StringReader(" [");
      ExtendedBufferedReader extendedBufferedReader0 = new ExtendedBufferedReader(stringReader0);
      CSVLexer1306663 cSVLexer1306663_0 = new CSVLexer1306663(cSVFormat0, extendedBufferedReader0);
      boolean boolean0 = cSVLexer1306663_0.isStartOfLine(13);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      CSVFormat cSVFormat0 = CSVFormat.TDF;
      StringReader stringReader0 = new StringReader("!\"?n+ZE=Q!Wtg");
      ExtendedBufferedReader extendedBufferedReader0 = new ExtendedBufferedReader(stringReader0);
      CSVLexer1306663 cSVLexer1306663_0 = new CSVLexer1306663(cSVFormat0, extendedBufferedReader0);
      Token token0 = new Token();
      Token token1 = cSVLexer1306663_0.nextToken(token0);
      assertSame(token0, token1);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      CSVFormat cSVFormat0 = CSVFormat.EXCEL;
      StringReader stringReader0 = new StringReader(" [");
      ExtendedBufferedReader extendedBufferedReader0 = new ExtendedBufferedReader(stringReader0);
      CSVLexer1 cSVLexer1_0 = new CSVLexer1(cSVFormat0, extendedBufferedReader0);
      boolean boolean0 = cSVLexer1_0.isEscape(65534);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      CSVFormat cSVFormat0 = CSVFormat.RFC4180;
      CSVLexer1306667 cSVLexer1306667_0 = new CSVLexer1306667(cSVFormat0, (ExtendedBufferedReader) null);
      // Undeclared exception!
      try { 
        cSVLexer1306667_0.getLineNumber();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      CSVFormat cSVFormat0 = CSVFormat.EXCEL;
      CSVLexer1306663 cSVLexer1306663_0 = new CSVLexer1306663(cSVFormat0, (ExtendedBufferedReader) null);
      // Undeclared exception!
      try { 
        cSVLexer1306663_0.readEscape();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      CSVFormat cSVFormat0 = CSVFormat.DEFAULT;
      StringReader stringReader0 = new StringReader("HrH.&84Pr");
      ExtendedBufferedReader extendedBufferedReader0 = new ExtendedBufferedReader(stringReader0);
      CSVLexer1306667 cSVLexer1306667_0 = new CSVLexer1306667(cSVFormat0, extendedBufferedReader0);
      // Undeclared exception!
      try { 
        cSVLexer1306667_0.trimTrailingSpaces((StringBuilder) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      CSVFormat cSVFormat0 = CSVFormat.DEFAULT;
      Reader reader0 = Reader.nullReader();
      ExtendedBufferedReader extendedBufferedReader0 = new ExtendedBufferedReader(reader0);
      CSVLexer1 cSVLexer1_0 = new CSVLexer1(cSVFormat0, extendedBufferedReader0);
      boolean boolean0 = cSVLexer1_0.isCommentStart(0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      CSVFormat cSVFormat0 = CSVFormat.EXCEL;
      StringReader stringReader0 = new StringReader(" [");
      ExtendedBufferedReader extendedBufferedReader0 = new ExtendedBufferedReader(stringReader0);
      CSVLexer1306663 cSVLexer1306663_0 = new CSVLexer1306663(cSVFormat0, extendedBufferedReader0);
      boolean boolean0 = cSVLexer1306663_0.isDelimiter((-1655));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Character character0 = Character.valueOf('<');
      Quote quote0 = Quote.NONE;
      String[] stringArray0 = new String[8];
      CSVFormat cSVFormat0 = new CSVFormat('<', character0, quote0, character0, character0, false, false, "H", "H", stringArray0);
      StringReader stringReader0 = new StringReader("ptMQi,4&D W4RXYV&o");
      ExtendedBufferedReader extendedBufferedReader0 = new ExtendedBufferedReader(stringReader0);
      CSVLexer cSVLexer0 = new CSVLexer(cSVFormat0, extendedBufferedReader0);
      boolean boolean0 = cSVLexer0.isDelimiter('<');
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Character character0 = Character.valueOf('<');
      Quote quote0 = Quote.NONE;
      String[] stringArray0 = new String[8];
      CSVFormat cSVFormat0 = new CSVFormat('<', character0, quote0, character0, character0, true, true, "H", "H", stringArray0);
      StringReader stringReader0 = new StringReader("ptMQNi,4&D W4RXYV&o");
      ExtendedBufferedReader extendedBufferedReader0 = new ExtendedBufferedReader(stringReader0);
      CSVLexer1306663 cSVLexer1306663_0 = new CSVLexer1306663(cSVFormat0, extendedBufferedReader0);
      boolean boolean0 = cSVLexer1306663_0.isEndOfFile(0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      CSVFormat cSVFormat0 = CSVFormat.TDF;
      StringReader stringReader0 = new StringReader("!\"?n+ZE=Q!Wtg");
      ExtendedBufferedReader extendedBufferedReader0 = new ExtendedBufferedReader(stringReader0);
      CSVLexer1306663 cSVLexer1306663_0 = new CSVLexer1306663(cSVFormat0, extendedBufferedReader0);
      boolean boolean0 = cSVLexer1306663_0.isEndOfFile((-1));
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      CSVFormat cSVFormat0 = CSVFormat.RFC4180;
      StringReader stringReader0 = new StringReader("org.apache.commons.csv.CSVParser$2");
      ExtendedBufferedReader extendedBufferedReader0 = new ExtendedBufferedReader(stringReader0);
      CSVLexer1306663 cSVLexer1306663_0 = new CSVLexer1306663(cSVFormat0, extendedBufferedReader0);
      boolean boolean0 = cSVLexer1306663_0.isEscape((-66));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      CSVFormat cSVFormat0 = CSVFormat.RFC4180;
      Reader reader0 = Reader.nullReader();
      ExtendedBufferedReader extendedBufferedReader0 = new ExtendedBufferedReader(reader0);
      CSVLexer1306663 cSVLexer1306663_0 = new CSVLexer1306663(cSVFormat0, extendedBufferedReader0);
      boolean boolean0 = cSVLexer1306663_0.isQuoteChar(101);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      CSVFormat cSVFormat0 = CSVFormat.TDF;
      StringReader stringReader0 = new StringReader("!\"?n+ZE=Q!Wtg");
      ExtendedBufferedReader extendedBufferedReader0 = new ExtendedBufferedReader(stringReader0);
      CSVLexer cSVLexer0 = new CSVLexer(cSVFormat0, extendedBufferedReader0);
      boolean boolean0 = cSVLexer0.isQuoteChar(34);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      CSVFormat cSVFormat0 = CSVFormat.TDF;
      Reader reader0 = Reader.nullReader();
      ExtendedBufferedReader extendedBufferedReader0 = new ExtendedBufferedReader(reader0);
      CSVLexer1 cSVLexer1_0 = new CSVLexer1(cSVFormat0, extendedBufferedReader0);
      boolean boolean0 = cSVLexer1_0.isWhitespace(12);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      CSVFormat cSVFormat0 = CSVFormat.RFC4180;
      StringReader stringReader0 = new StringReader("org.apache.commons.csv.CSVParser$2");
      ExtendedBufferedReader extendedBufferedReader0 = new ExtendedBufferedReader(stringReader0);
      extendedBufferedReader0.read();
      CSVLexer1306663 cSVLexer1306663_0 = new CSVLexer1306663(cSVFormat0, extendedBufferedReader0);
      Token token0 = new Token();
      Token token1 = cSVLexer1306663_0.nextToken(token0);
      assertSame(token1, token0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      CSVFormat cSVFormat0 = CSVFormat.EXCEL;
      CSVLexer cSVLexer0 = new CSVLexer(cSVFormat0, (ExtendedBufferedReader) null);
      boolean boolean0 = cSVLexer0.isStartOfLine((-1114));
      assertFalse(boolean0);
  }
}
