/*
 * This file was automatically generated by EvoSuite
 * Thu Oct 01 06:43:57 GMT 2026
 */

package org.apache.commons.collections4.trie;

import org.junit.Test;
import static org.junit.Assert.*;
import java.nio.CharBuffer;
import org.apache.commons.collections4.Trie;
import org.apache.commons.collections4.trie.UnmodifiableTrie;

public class UnmodifiableTrie_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try { 
        UnmodifiableTrie.unmodifiableTrie((Trie<Object, ? extends CharBuffer>) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Trie must not be null
         //
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      UnmodifiableTrie<Object, Integer> unmodifiableTrie0 = null;
      try {
        unmodifiableTrie0 = new UnmodifiableTrie<Object, Integer>((Trie<Object, ? extends Integer>) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Trie must not be null
         //
      }
  }
}
