/*
 * This file was automatically generated by EvoSuite
 * Fri Oct 02 04:28:11 GMT 2026
 */

package com.google.javascript.jscomp;

import org.junit.Test;
import static org.junit.Assert.*;
import com.google.javascript.jscomp.AbstractCompiler;
import com.google.javascript.jscomp.Compiler;
import com.google.javascript.jscomp.DenormalizeTest;
import com.google.javascript.jscomp.InlineVariables;
import com.google.javascript.rhino.Node;

public class InlineVariables_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DenormalizeTest denormalizeTest0 = new DenormalizeTest();
      Compiler compiler0 = denormalizeTest0.createCompiler();
      InlineVariables.Mode inlineVariables_Mode0 = InlineVariables.Mode.LOCALS_ONLY;
      InlineVariables inlineVariables0 = new InlineVariables(compiler0, inlineVariables_Mode0, true);
      Node node0 = Node.newNumber((-672.22094));
      // Undeclared exception!
      try { 
        inlineVariables0.process(node0, node0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      InlineVariables.Mode inlineVariables_Mode0 = InlineVariables.Mode.ALL;
      InlineVariables inlineVariables0 = new InlineVariables((AbstractCompiler) null, inlineVariables_Mode0, true);
      // Undeclared exception!
      try { 
        inlineVariables0.process((Node) null, (Node) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }
}
