/*
 * This file was automatically generated by EvoSuite
 * Thu Oct 01 06:41:08 GMT 2026
 */

package org.apache.commons.collections4.map;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.AbstractMap;
import java.util.Collection;
import java.util.HashMap;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Set;
import org.apache.commons.collections4.OrderedMapIterator;
import org.apache.commons.collections4.map.ListOrderedMap;

public class ListOrderedMap_ESTest {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      ListOrderedMap<HashMap<Object, Integer>, Object> listOrderedMap0 = new ListOrderedMap<HashMap<Object, Integer>, Object>();
      ListOrderedMap.ListOrderedMapIterator<HashMap<Object, Integer>, Object> listOrderedMap_ListOrderedMapIterator0 = new ListOrderedMap.ListOrderedMapIterator<HashMap<Object, Integer>, Object>(listOrderedMap0);
      listOrderedMap_ListOrderedMapIterator0.reset();
      assertFalse(listOrderedMap_ListOrderedMapIterator0.hasNext());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      ListOrderedMap<Object, Integer> listOrderedMap0 = new ListOrderedMap<Object, Integer>();
      ListOrderedMap.ListOrderedMapIterator<Object, Integer> listOrderedMap_ListOrderedMapIterator0 = new ListOrderedMap.ListOrderedMapIterator<Object, Integer>(listOrderedMap0);
      boolean boolean0 = listOrderedMap_ListOrderedMapIterator0.hasPrevious();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      ListOrderedMap<Integer, Map.Entry<Integer, Integer>> listOrderedMap0 = new ListOrderedMap<Integer, Map.Entry<Integer, Integer>>();
      ListOrderedMap.ListOrderedMapIterator<Integer, Map.Entry<Integer, Integer>> listOrderedMap_ListOrderedMapIterator0 = new ListOrderedMap.ListOrderedMapIterator<Integer, Map.Entry<Integer, Integer>>(listOrderedMap0);
      // Undeclared exception!
      try { 
        listOrderedMap_ListOrderedMapIterator0.next();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      HashMap<Object, HashMap<Object, Object>> hashMap0 = new HashMap<Object, HashMap<Object, Object>>(125);
      ListOrderedMap<Object, HashMap<Object, Object>> listOrderedMap0 = ListOrderedMap.listOrderedMap((Map<Object, HashMap<Object, Object>>) hashMap0);
      ListOrderedMap.ListOrderedMapIterator<Object, HashMap<Object, Object>> listOrderedMap_ListOrderedMapIterator0 = new ListOrderedMap.ListOrderedMapIterator<Object, HashMap<Object, Object>>(listOrderedMap0);
      // Undeclared exception!
      try { 
        listOrderedMap_ListOrderedMapIterator0.previous();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      HashMap<Object, Object> hashMap0 = new HashMap<Object, Object>();
      ListOrderedMap<Object, Object> listOrderedMap0 = ListOrderedMap.listOrderedMap((Map<Object, Object>) hashMap0);
      ListOrderedMap.ListOrderedMapIterator<Object, Object> listOrderedMap_ListOrderedMapIterator0 = new ListOrderedMap.ListOrderedMapIterator<Object, Object>(listOrderedMap0);
      boolean boolean0 = listOrderedMap_ListOrderedMapIterator0.hasNext();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      ListOrderedMap<Integer, Integer> listOrderedMap0 = new ListOrderedMap<Integer, Integer>();
      ListOrderedMap.ValuesView<Integer> listOrderedMap_ValuesView0 = new ListOrderedMap.ValuesView<Integer>(listOrderedMap0);
      ListOrderedMap.EntrySetView<Integer, Integer> listOrderedMap_EntrySetView0 = new ListOrderedMap.EntrySetView<Integer, Integer>(listOrderedMap0, listOrderedMap_ValuesView0);
      listOrderedMap_EntrySetView0.clear();
      assertTrue(listOrderedMap_EntrySetView0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      HashMap<Map.Entry<Object, Object>, Object> hashMap0 = new HashMap<Map.Entry<Object, Object>, Object>();
      ListOrderedMap<Map.Entry<Object, Object>, Object> listOrderedMap0 = ListOrderedMap.listOrderedMap((Map<Map.Entry<Object, Object>, Object>) hashMap0);
      LinkedList<Map.Entry<Object, Object>> linkedList0 = new LinkedList<Map.Entry<Object, Object>>();
      ListOrderedMap.EntrySetView<Map.Entry<Object, Object>, Object> listOrderedMap_EntrySetView0 = new ListOrderedMap.EntrySetView<Map.Entry<Object, Object>, Object>(listOrderedMap0, linkedList0);
      int int0 = listOrderedMap_EntrySetView0.size();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      HashMap<Object, Map.Entry<Integer, Integer>> hashMap0 = new HashMap<Object, Map.Entry<Integer, Integer>>();
      ListOrderedMap<Object, Map.Entry<Integer, Integer>> listOrderedMap0 = new ListOrderedMap<Object, Map.Entry<Integer, Integer>>(hashMap0);
      ListOrderedMap<Object, Map.Entry<Object, Integer>> listOrderedMap1 = new ListOrderedMap<Object, Map.Entry<Object, Integer>>();
      List<Object> list0 = listOrderedMap1.keyList();
      ListOrderedMap.EntrySetView<Object, Map.Entry<Integer, Integer>> listOrderedMap_EntrySetView0 = new ListOrderedMap.EntrySetView<Object, Map.Entry<Integer, Integer>>(listOrderedMap0, list0);
      String string0 = listOrderedMap_EntrySetView0.toString();
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      ListOrderedMap<Object, Integer> listOrderedMap0 = new ListOrderedMap<Object, Integer>();
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      ListOrderedMap.EntrySetView<Object, Integer> listOrderedMap_EntrySetView0 = new ListOrderedMap.EntrySetView<Object, Integer>(listOrderedMap0, linkedList0);
      boolean boolean0 = listOrderedMap_EntrySetView0.isEmpty();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      HashMap<Object, Map.Entry<Integer, Object>> hashMap0 = new HashMap<Object, Map.Entry<Integer, Object>>(0);
      ListOrderedMap<Object, Map.Entry<Integer, Object>> listOrderedMap0 = new ListOrderedMap<Object, Map.Entry<Integer, Object>>(hashMap0);
      OrderedMapIterator<Object, Map.Entry<Integer, Object>> orderedMapIterator0 = listOrderedMap0.mapIterator();
      assertFalse(orderedMapIterator0.hasPrevious());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      ListOrderedMap<Object, Integer> listOrderedMap0 = new ListOrderedMap<Object, Integer>();
      // Undeclared exception!
      try { 
        listOrderedMap0.remove((-1));
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      ListOrderedMap<HashMap<Integer, Integer>, Integer> listOrderedMap0 = new ListOrderedMap<HashMap<Integer, Integer>, Integer>();
      Collection<Integer> collection0 = listOrderedMap0.values();
      assertNotNull(collection0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      ListOrderedMap<Object, Map.Entry<Integer, Integer>> listOrderedMap0 = new ListOrderedMap<Object, Map.Entry<Integer, Integer>>();
      // Undeclared exception!
      try { 
        listOrderedMap0.getValue((-2136));
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      ListOrderedMap<HashMap<Integer, Object>, Integer> listOrderedMap0 = new ListOrderedMap<HashMap<Integer, Object>, Integer>();
      Integer integer0 = new Integer((-1685));
      // Undeclared exception!
      try { 
        listOrderedMap0.setValue((-1685), integer0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      ListOrderedMap<Map.Entry<Integer, Object>, Integer> listOrderedMap0 = new ListOrderedMap<Map.Entry<Integer, Object>, Integer>();
      int int0 = listOrderedMap0.indexOf((Object) null);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      ListOrderedMap<Object, Integer> listOrderedMap0 = new ListOrderedMap<Object, Integer>();
      ListOrderedMap.ValuesView<Integer> listOrderedMap_ValuesView0 = new ListOrderedMap.ValuesView<Integer>(listOrderedMap0);
      Iterator<Integer> iterator0 = listOrderedMap_ValuesView0.iterator();
      assertNotNull(iterator0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      HashMap<HashMap<Integer, Integer>, Integer> hashMap0 = new HashMap<HashMap<Integer, Integer>, Integer>();
      ListOrderedMap<HashMap<Integer, Integer>, Integer> listOrderedMap0 = new ListOrderedMap<HashMap<Integer, Integer>, Integer>(hashMap0);
      List<HashMap<Integer, Integer>> list0 = listOrderedMap0.keyList();
      ListOrderedMap.ListOrderedIterator<HashMap<Integer, Integer>, Integer> listOrderedMap_ListOrderedIterator0 = new ListOrderedMap.ListOrderedIterator<HashMap<Integer, Integer>, Integer>(listOrderedMap0, list0);
      // Undeclared exception!
      try { 
        listOrderedMap_ListOrderedIterator0.remove();
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // remove() is not supported
         //
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      HashMap<Object, Integer> hashMap0 = new HashMap<Object, Integer>();
      ListOrderedMap<Object, Integer> listOrderedMap0 = new ListOrderedMap<Object, Integer>(hashMap0);
      Integer integer0 = new Integer((-582));
      listOrderedMap0.put((Object) hashMap0, integer0);
      ListOrderedMap<Integer, Object> listOrderedMap1 = new ListOrderedMap<Integer, Object>();
      ListOrderedMap.ValuesView<Integer> listOrderedMap_ValuesView0 = new ListOrderedMap.ValuesView<Integer>(listOrderedMap0);
      ListOrderedMap.ListOrderedIterator<Integer, Object> listOrderedMap_ListOrderedIterator0 = new ListOrderedMap.ListOrderedIterator<Integer, Object>(listOrderedMap1, listOrderedMap_ValuesView0);
      // Undeclared exception!
      try { 
        listOrderedMap_ListOrderedIterator0.next();
        fail("Expecting exception: StackOverflowError");
      
      } catch(StackOverflowError e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      ListOrderedMap<Map.Entry<Integer, Object>, Integer> listOrderedMap0 = new ListOrderedMap<Map.Entry<Integer, Object>, Integer>();
      ListOrderedMap<Object, Object> listOrderedMap1 = new ListOrderedMap<Object, Object>();
      ListOrderedMap.ListOrderedMapEntry<Object, Object> listOrderedMap_ListOrderedMapEntry0 = new ListOrderedMap.ListOrderedMapEntry<Object, Object>(listOrderedMap1, (Object) null);
      Object object0 = listOrderedMap_ListOrderedMapEntry0.setValue(listOrderedMap0);
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      ListOrderedMap<Object, Integer> listOrderedMap0 = new ListOrderedMap<Object, Integer>();
      ListOrderedMap<Object, HashMap<Integer, Integer>> listOrderedMap1 = new ListOrderedMap<Object, HashMap<Integer, Integer>>();
      ListOrderedMap.ValuesView<HashMap<Integer, Integer>> listOrderedMap_ValuesView0 = new ListOrderedMap.ValuesView<HashMap<Integer, Integer>>(listOrderedMap1);
      boolean boolean0 = listOrderedMap_ValuesView0.contains(listOrderedMap0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      ListOrderedMap<Object, HashMap<Integer, Object>> listOrderedMap0 = new ListOrderedMap<Object, HashMap<Integer, Object>>();
      ListOrderedMap.ValuesView<HashMap<Integer, Object>> listOrderedMap_ValuesView0 = new ListOrderedMap.ValuesView<HashMap<Integer, Object>>(listOrderedMap0);
      HashMap<Integer, Object> hashMap0 = new HashMap<Integer, Object>();
      // Undeclared exception!
      try { 
        listOrderedMap_ValuesView0.set(0, hashMap0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      ListOrderedMap<Object, Object> listOrderedMap0 = new ListOrderedMap<Object, Object>();
      ListOrderedMap.ValuesView<Object> listOrderedMap_ValuesView0 = new ListOrderedMap.ValuesView<Object>(listOrderedMap0);
      // Undeclared exception!
      try { 
        listOrderedMap_ValuesView0.get((-1));
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      ListOrderedMap<Object, Object> listOrderedMap0 = new ListOrderedMap<Object, Object>();
      ListOrderedMap.ValuesView<Object> listOrderedMap_ValuesView0 = new ListOrderedMap.ValuesView<Object>(listOrderedMap0);
      int int0 = listOrderedMap_ValuesView0.size();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      ListOrderedMap<Integer, Integer> listOrderedMap0 = new ListOrderedMap<Integer, Integer>();
      ListOrderedMap.ValuesView<Integer> listOrderedMap_ValuesView0 = new ListOrderedMap.ValuesView<Integer>(listOrderedMap0);
      // Undeclared exception!
      try { 
        listOrderedMap_ValuesView0.remove(0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      ListOrderedMap<Integer, Integer> listOrderedMap0 = new ListOrderedMap<Integer, Integer>();
      ListOrderedMap.ValuesView<Integer> listOrderedMap_ValuesView0 = new ListOrderedMap.ValuesView<Integer>(listOrderedMap0);
      listOrderedMap_ValuesView0.clear();
      assertEquals(0, listOrderedMap_ValuesView0.size());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      HashMap<Object, Integer> hashMap0 = new HashMap<Object, Integer>();
      HashMap<Integer, Integer> hashMap1 = new HashMap<Integer, Integer>();
      HashMap<HashMap<Integer, Integer>, HashMap<Object, Integer>> hashMap2 = new HashMap<HashMap<Integer, Integer>, HashMap<Object, Integer>>();
      hashMap2.put(hashMap1, hashMap0);
      ListOrderedMap<HashMap<Integer, Integer>, HashMap<Object, Integer>> listOrderedMap0 = new ListOrderedMap<HashMap<Integer, Integer>, HashMap<Object, Integer>>(hashMap2);
      ListOrderedMap<HashMap<Integer, Integer>, HashMap<Object, Integer>> listOrderedMap1 = new ListOrderedMap<HashMap<Integer, Integer>, HashMap<Object, Integer>>(listOrderedMap0);
      assertFalse(listOrderedMap1.isEmpty());
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      ListOrderedMap<Integer, Integer> listOrderedMap0 = new ListOrderedMap<Integer, Integer>();
      ListOrderedMap.KeySetView<Integer> listOrderedMap_KeySetView0 = new ListOrderedMap.KeySetView<Integer>(listOrderedMap0);
      Iterator<Integer> iterator0 = listOrderedMap_KeySetView0.iterator();
      ListOrderedMap.KeySetView<Integer> listOrderedMap_KeySetView1 = new ListOrderedMap.KeySetView<Integer>(listOrderedMap0);
      boolean boolean0 = listOrderedMap_KeySetView1.contains(iterator0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      ListOrderedMap<Integer, Integer> listOrderedMap0 = new ListOrderedMap<Integer, Integer>();
      ListOrderedMap.KeySetView<Integer> listOrderedMap_KeySetView0 = new ListOrderedMap.KeySetView<Integer>(listOrderedMap0);
      listOrderedMap_KeySetView0.clear();
      assertEquals(0, listOrderedMap_KeySetView0.size());
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      ListOrderedMap<Map.Entry<Integer, Integer>, Object> listOrderedMap0 = new ListOrderedMap<Map.Entry<Integer, Integer>, Object>();
      Integer integer0 = new Integer((-2895));
      AbstractMap.SimpleImmutableEntry<Integer, Integer> abstractMap_SimpleImmutableEntry0 = new AbstractMap.SimpleImmutableEntry<Integer, Integer>((Integer) null, integer0);
      AbstractMap.SimpleImmutableEntry<Integer, Integer> abstractMap_SimpleImmutableEntry1 = new AbstractMap.SimpleImmutableEntry<Integer, Integer>(abstractMap_SimpleImmutableEntry0);
      listOrderedMap0.putIfAbsent(abstractMap_SimpleImmutableEntry1, integer0);
      Map.Entry<Integer, Integer> map_Entry0 = listOrderedMap0.firstKey();
      assertNotNull(map_Entry0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      ListOrderedMap<Integer, Object> listOrderedMap0 = new ListOrderedMap<Integer, Object>();
      // Undeclared exception!
      try { 
        listOrderedMap0.firstKey();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // Map is empty
         //
      }
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      ListOrderedMap<Integer, Object> listOrderedMap0 = new ListOrderedMap<Integer, Object>();
      // Undeclared exception!
      try { 
        listOrderedMap0.lastKey();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // Map is empty
         //
      }
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      ListOrderedMap<Integer, Object> listOrderedMap0 = new ListOrderedMap<Integer, Object>();
      Integer integer0 = listOrderedMap0.previousKey((Object) null);
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      ListOrderedMap<Integer, Object> listOrderedMap0 = new ListOrderedMap<Integer, Object>();
      HashMap<Integer, Integer> hashMap0 = new HashMap<Integer, Integer>();
      Integer integer0 = new Integer(0);
      hashMap0.put(integer0, integer0);
      listOrderedMap0.putAll((Map<? extends Integer, ?>) hashMap0);
      assertFalse(listOrderedMap0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      HashMap<Map.Entry<Object, Integer>, Integer> hashMap0 = new HashMap<Map.Entry<Object, Integer>, Integer>();
      ListOrderedMap<Map.Entry<Object, Integer>, Integer> listOrderedMap0 = ListOrderedMap.listOrderedMap((Map<Map.Entry<Object, Integer>, Integer>) hashMap0);
      listOrderedMap0.putAll((-1143), (Map<? extends Map.Entry<Object, Integer>, ? extends Integer>) listOrderedMap0);
      assertEquals(0, listOrderedMap0.size());
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      HashMap<Object, HashMap<Object, Integer>> hashMap0 = new HashMap<Object, HashMap<Object, Integer>>();
      Integer integer0 = new Integer(0);
      HashMap<Object, Integer> hashMap1 = new HashMap<Object, Integer>();
      hashMap0.put(integer0, hashMap1);
      ListOrderedMap<Object, HashMap<Object, Integer>> listOrderedMap0 = ListOrderedMap.listOrderedMap((Map<Object, HashMap<Object, Integer>>) hashMap0);
      listOrderedMap0.putAll(0, (Map<?, ? extends HashMap<Object, Integer>>) hashMap0);
      assertFalse(hashMap0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      ListOrderedMap<Object, Integer> listOrderedMap0 = new ListOrderedMap<Object, Integer>();
      Integer integer0 = listOrderedMap0.remove((Object) listOrderedMap0);
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      ListOrderedMap<Object, Integer> listOrderedMap0 = new ListOrderedMap<Object, Integer>();
      String string0 = listOrderedMap0.toString();
      assertEquals("{}", string0);
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      HashMap<Integer, Integer> hashMap0 = new HashMap<Integer, Integer>(1508);
      ListOrderedMap<Integer, Integer> listOrderedMap0 = new ListOrderedMap<Integer, Integer>(hashMap0);
      Integer integer0 = listOrderedMap0.nextKey(hashMap0);
      // Undeclared exception!
      try { 
        listOrderedMap0.put(1508, integer0, integer0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 1508, Size: 0
         //
      }
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      ListOrderedMap<Integer, HashMap<Integer, Integer>> listOrderedMap0 = new ListOrderedMap<Integer, HashMap<Integer, Integer>>();
      ListOrderedMap<Integer, HashMap<Integer, Integer>> listOrderedMap1 = ListOrderedMap.listOrderedMap((Map<Integer, HashMap<Integer, Integer>>) listOrderedMap0);
      HashMap<Object, Integer> hashMap0 = new HashMap<Object, Integer>();
      ListOrderedMap<Object, Integer> listOrderedMap2 = new ListOrderedMap<Object, Integer>(hashMap0);
      List<Integer> list0 = listOrderedMap2.valueList();
      ListOrderedMap.EntrySetView<Integer, HashMap<Integer, Integer>> listOrderedMap_EntrySetView0 = new ListOrderedMap.EntrySetView<Integer, HashMap<Integer, Integer>>(listOrderedMap1, list0);
      HashMap<Integer, Integer> hashMap1 = new HashMap<Integer, Integer>();
      boolean boolean0 = listOrderedMap_EntrySetView0.equals(hashMap1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      ListOrderedMap<Integer, Object> listOrderedMap0 = new ListOrderedMap<Integer, Object>();
      HashMap<Integer, Integer> hashMap0 = new HashMap<Integer, Integer>();
      ListOrderedMap<Integer, Integer> listOrderedMap1 = ListOrderedMap.listOrderedMap((Map<Integer, Integer>) hashMap0);
      ListOrderedMap.ValuesView<Integer> listOrderedMap_ValuesView0 = new ListOrderedMap.ValuesView<Integer>(listOrderedMap1);
      ListOrderedMap.EntrySetView<Integer, Object> listOrderedMap_EntrySetView0 = new ListOrderedMap.EntrySetView<Integer, Object>(listOrderedMap0, listOrderedMap_ValuesView0);
      boolean boolean0 = listOrderedMap_EntrySetView0.contains((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      ListOrderedMap<Integer, Integer> listOrderedMap0 = new ListOrderedMap<Integer, Integer>();
      ListOrderedMap.ValuesView<Integer> listOrderedMap_ValuesView0 = new ListOrderedMap.ValuesView<Integer>(listOrderedMap0);
      ListOrderedMap<Map.Entry<Object, Object>, HashMap<Integer, Object>> listOrderedMap1 = new ListOrderedMap<Map.Entry<Object, Object>, HashMap<Integer, Object>>();
      AbstractMap.SimpleEntry<Object, Object> abstractMap_SimpleEntry0 = new AbstractMap.SimpleEntry<Object, Object>(listOrderedMap1, listOrderedMap_ValuesView0);
      List<Map.Entry<Object, Object>> list0 = List.of((Map.Entry<Object, Object>) abstractMap_SimpleEntry0, (Map.Entry<Object, Object>) abstractMap_SimpleEntry0, (Map.Entry<Object, Object>) abstractMap_SimpleEntry0, (Map.Entry<Object, Object>) abstractMap_SimpleEntry0, (Map.Entry<Object, Object>) abstractMap_SimpleEntry0, (Map.Entry<Object, Object>) abstractMap_SimpleEntry0, (Map.Entry<Object, Object>) abstractMap_SimpleEntry0, (Map.Entry<Object, Object>) abstractMap_SimpleEntry0);
      ListOrderedMap.EntrySetView<Map.Entry<Object, Object>, HashMap<Integer, Object>> listOrderedMap_EntrySetView0 = new ListOrderedMap.EntrySetView<Map.Entry<Object, Object>, HashMap<Integer, Object>>(listOrderedMap1, list0);
      boolean boolean0 = listOrderedMap_EntrySetView0.containsAll(listOrderedMap_ValuesView0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      ListOrderedMap<Integer, Integer> listOrderedMap0 = new ListOrderedMap<Integer, Integer>();
      List<Integer> list0 = listOrderedMap0.asList();
      ListOrderedMap.EntrySetView<Integer, Integer> listOrderedMap_EntrySetView0 = new ListOrderedMap.EntrySetView<Integer, Integer>(listOrderedMap0, list0);
      boolean boolean0 = listOrderedMap_EntrySetView0.remove(listOrderedMap0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      ListOrderedMap<HashMap<Integer, Integer>, Integer> listOrderedMap0 = new ListOrderedMap<HashMap<Integer, Integer>, Integer>();
      ListOrderedMap.ListOrderedMapIterator<HashMap<Integer, Integer>, Integer> listOrderedMap_ListOrderedMapIterator0 = new ListOrderedMap.ListOrderedMapIterator<HashMap<Integer, Integer>, Integer>(listOrderedMap0);
      // Undeclared exception!
      try { 
        listOrderedMap_ListOrderedMapIterator0.remove();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // remove() can only be called once after next()
         //
      }
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      HashMap<Integer, Map.Entry<Integer, Integer>> hashMap0 = new HashMap<Integer, Map.Entry<Integer, Integer>>();
      ListOrderedMap<Integer, Map.Entry<Integer, Integer>> listOrderedMap0 = ListOrderedMap.listOrderedMap((Map<Integer, Map.Entry<Integer, Integer>>) hashMap0);
      ListOrderedMap.ListOrderedMapIterator<Integer, Map.Entry<Integer, Integer>> listOrderedMap_ListOrderedMapIterator0 = new ListOrderedMap.ListOrderedMapIterator<Integer, Map.Entry<Integer, Integer>>(listOrderedMap0);
      // Undeclared exception!
      try { 
        listOrderedMap_ListOrderedMapIterator0.getKey();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // getKey() can only be called after next() and before remove()
         //
      }
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      ListOrderedMap<HashMap<Object, Integer>, Object> listOrderedMap0 = new ListOrderedMap<HashMap<Object, Integer>, Object>();
      ListOrderedMap.ListOrderedMapIterator<HashMap<Object, Integer>, Object> listOrderedMap_ListOrderedMapIterator0 = new ListOrderedMap.ListOrderedMapIterator<HashMap<Object, Integer>, Object>(listOrderedMap0);
      // Undeclared exception!
      try { 
        listOrderedMap_ListOrderedMapIterator0.getValue();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // getValue() can only be called after next() and before remove()
         //
      }
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      ListOrderedMap<HashMap<Integer, Integer>, Integer> listOrderedMap0 = new ListOrderedMap<HashMap<Integer, Integer>, Integer>();
      ListOrderedMap.ListOrderedMapIterator<HashMap<Integer, Integer>, Integer> listOrderedMap_ListOrderedMapIterator0 = new ListOrderedMap.ListOrderedMapIterator<HashMap<Integer, Integer>, Integer>(listOrderedMap0);
      Integer integer0 = new Integer((-543));
      // Undeclared exception!
      try { 
        listOrderedMap_ListOrderedMapIterator0.setValue(integer0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // setValue() can only be called after next() and before remove()
         //
      }
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      ListOrderedMap<Object, HashMap<Integer, Integer>> listOrderedMap0 = new ListOrderedMap<Object, HashMap<Integer, Integer>>();
      ListOrderedMap.ListOrderedMapIterator<Object, HashMap<Integer, Integer>> listOrderedMap_ListOrderedMapIterator0 = new ListOrderedMap.ListOrderedMapIterator<Object, HashMap<Integer, Integer>>(listOrderedMap0);
      String string0 = listOrderedMap_ListOrderedMapIterator0.toString();
      assertEquals("Iterator[]", string0);
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      ListOrderedMap<Object, Integer> listOrderedMap0 = new ListOrderedMap<Object, Integer>();
      listOrderedMap0.clear();
      assertEquals(0, listOrderedMap0.size());
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      HashMap<HashMap<Integer, Integer>, HashMap<Object, Integer>> hashMap0 = new HashMap<HashMap<Integer, Integer>, HashMap<Object, Integer>>();
      ListOrderedMap<HashMap<Integer, Integer>, HashMap<Object, Integer>> listOrderedMap0 = new ListOrderedMap<HashMap<Integer, Integer>, HashMap<Object, Integer>>(hashMap0);
      Set<HashMap<Integer, Integer>> set0 = listOrderedMap0.keySet();
      assertEquals(0, set0.size());
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      HashMap<Integer, Integer> hashMap0 = new HashMap<Integer, Integer>();
      ListOrderedMap<Integer, Integer> listOrderedMap0 = new ListOrderedMap<Integer, Integer>(hashMap0);
      Set<Map.Entry<Integer, Integer>> set0 = (Set<Map.Entry<Integer, Integer>>)listOrderedMap0.entrySet();
      assertTrue(set0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      ListOrderedMap<Object, Integer> listOrderedMap0 = new ListOrderedMap<Object, Integer>();
      // Undeclared exception!
      try { 
        listOrderedMap0.get(1976);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      ListOrderedMap<Object, Integer> listOrderedMap0 = null;
      try {
        listOrderedMap0 = new ListOrderedMap<Object, Integer>((Map<Object, Integer>) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Map must not be null
         //
      }
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      // Undeclared exception!
      try { 
        ListOrderedMap.listOrderedMap((Map<Integer, Object>) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Map must not be null
         //
      }
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      HashMap<Integer, Object> hashMap0 = new HashMap<Integer, Object>();
      ListOrderedMap<Integer, Object> listOrderedMap0 = ListOrderedMap.listOrderedMap((Map<Integer, Object>) hashMap0);
      Integer integer0 = new Integer(1473);
      hashMap0.put(integer0, integer0);
      Set<Map.Entry<Integer, Object>> set0 = (Set<Map.Entry<Integer, Object>>)listOrderedMap0.entrySet();
      assertEquals(1, set0.size());
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      HashMap<Object, Integer> hashMap0 = new HashMap<Object, Integer>();
      HashMap<HashMap<Integer, Integer>, HashMap<Object, Integer>> hashMap1 = new HashMap<HashMap<Integer, Integer>, HashMap<Object, Integer>>();
      ListOrderedMap<HashMap<Integer, Integer>, HashMap<Object, Integer>> listOrderedMap0 = new ListOrderedMap<HashMap<Integer, Integer>, HashMap<Object, Integer>>(hashMap1);
      HashMap<Integer, Integer> hashMap2 = new HashMap<Integer, Integer>();
      hashMap1.put(hashMap2, hashMap0);
      Set<HashMap<Integer, Integer>> set0 = listOrderedMap0.keySet();
      assertEquals(1, set0.size());
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      ListOrderedMap<HashMap<Object, Integer>, Integer> listOrderedMap0 = new ListOrderedMap<HashMap<Object, Integer>, Integer>();
      HashMap<Object, Integer> hashMap0 = new HashMap<Object, Integer>();
      Integer integer0 = new Integer(88);
      Integer integer1 = listOrderedMap0.put(0, hashMap0, integer0);
      assertNull(integer1);
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      Integer integer0 = new Integer((-155));
      HashMap<Integer, Map.Entry<Integer, Integer>> hashMap0 = new HashMap<Integer, Map.Entry<Integer, Integer>>();
      AbstractMap.SimpleEntry<Integer, Integer> abstractMap_SimpleEntry0 = new AbstractMap.SimpleEntry<Integer, Integer>(integer0, integer0);
      hashMap0.put(integer0, abstractMap_SimpleEntry0);
      ListOrderedMap<Integer, Map.Entry<Integer, Integer>> listOrderedMap0 = ListOrderedMap.listOrderedMap((Map<Integer, Map.Entry<Integer, Integer>>) hashMap0);
      List<Map.Entry<Integer, Integer>> list0 = listOrderedMap0.valueList();
      assertFalse(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test57()  throws Throwable  {
      HashMap<Integer, Integer> hashMap0 = new HashMap<Integer, Integer>();
      ListOrderedMap<Integer, Integer> listOrderedMap0 = new ListOrderedMap<Integer, Integer>(hashMap0);
      ListOrderedMap.ValuesView<Integer> listOrderedMap_ValuesView0 = new ListOrderedMap.ValuesView<Integer>(listOrderedMap0);
      ListOrderedMap.EntrySetView<Integer, Integer> listOrderedMap_EntrySetView0 = new ListOrderedMap.EntrySetView<Integer, Integer>(listOrderedMap0, listOrderedMap_ValuesView0);
      Iterator<Map.Entry<Integer, Integer>> iterator0 = (Iterator<Map.Entry<Integer, Integer>>)listOrderedMap_EntrySetView0.iterator();
      assertNotNull(iterator0);
  }

  @Test(timeout = 4000)
  public void test58()  throws Throwable  {
      ListOrderedMap<Integer, Integer> listOrderedMap0 = new ListOrderedMap<Integer, Integer>();
      ListOrderedMap.KeySetView<Integer> listOrderedMap_KeySetView0 = new ListOrderedMap.KeySetView<Integer>(listOrderedMap0);
      int int0 = listOrderedMap_KeySetView0.size();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test59()  throws Throwable  {
      ListOrderedMap<Integer, Object> listOrderedMap0 = new ListOrderedMap<Integer, Object>();
      ListOrderedMap.ListOrderedMapIterator<Integer, Object> listOrderedMap_ListOrderedMapIterator0 = new ListOrderedMap.ListOrderedMapIterator<Integer, Object>(listOrderedMap0);
      ListOrderedMap<Object, Integer> listOrderedMap1 = new ListOrderedMap<Object, Integer>();
      ListOrderedMap.ListOrderedMapEntry<Object, Integer> listOrderedMap_ListOrderedMapEntry0 = new ListOrderedMap.ListOrderedMapEntry<Object, Integer>(listOrderedMap1, listOrderedMap_ListOrderedMapIterator0);
      Integer integer0 = listOrderedMap_ListOrderedMapEntry0.getValue();
      assertNull(integer0);
  }
}
