/*
 * This file was automatically generated by EvoSuite
 * Thu Oct 01 23:43:16 GMT 2026
 */

package com.google.javascript.jscomp;

import org.junit.Test;
import static org.junit.Assert.*;
import com.google.common.base.Supplier;
import com.google.javascript.jscomp.AbstractCompiler;
import com.google.javascript.jscomp.Compiler;
import com.google.javascript.jscomp.DenormalizeTest;
import com.google.javascript.jscomp.InlineObjectLiterals;
import com.google.javascript.jscomp.RenameLabels;
import com.google.javascript.rhino.Node;

public class InlineObjectLiterals_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Compiler compiler0 = new Compiler();
      RenameLabels.DefaultNameSupplier renameLabels_DefaultNameSupplier0 = new RenameLabels.DefaultNameSupplier();
      InlineObjectLiterals inlineObjectLiterals0 = new InlineObjectLiterals(compiler0, renameLabels_DefaultNameSupplier0);
      Node node0 = compiler0.parseTestCode("JSCompiler_object_inline_");
      // Undeclared exception!
      try { 
        inlineObjectLiterals0.process(node0, node0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // INTERNAL COMPILER ERROR.
         // Please report this problem.
         // null
         //
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      DenormalizeTest denormalizeTest0 = new DenormalizeTest();
      denormalizeTest0.testInOperatorNotInsideFor();
      Compiler compiler0 = denormalizeTest0.getLastCompiler();
      InlineObjectLiterals inlineObjectLiterals0 = new InlineObjectLiterals(compiler0, (Supplier<String>) null);
      Node node0 = compiler0.jsRoot;
      inlineObjectLiterals0.process(node0, node0);
      assertEquals(1, Node.LEFT);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Compiler compiler0 = new Compiler();
      RenameLabels.DefaultNameSupplier renameLabels_DefaultNameSupplier0 = new RenameLabels.DefaultNameSupplier();
      InlineObjectLiterals inlineObjectLiterals0 = new InlineObjectLiterals(compiler0, renameLabels_DefaultNameSupplier0);
      Node node0 = compiler0.parseTestCode("JSCompiler_object_inline_");
      Node node1 = new Node((-2), node0, node0);
      // Undeclared exception!
      try { 
        inlineObjectLiterals0.process(node0, node1);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // -2
         //
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      RenameLabels.DefaultNameSupplier renameLabels_DefaultNameSupplier0 = new RenameLabels.DefaultNameSupplier();
      InlineObjectLiterals inlineObjectLiterals0 = new InlineObjectLiterals((AbstractCompiler) null, renameLabels_DefaultNameSupplier0);
      Node node0 = Node.newNumber((-1908.27463));
      // Undeclared exception!
      try { 
        inlineObjectLiterals0.process(node0, node0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }
}
